//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevLogHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMsg() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevLogHelper.Resources.ResourceMsg", typeof(ResourceMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请填写内容或关键字 的本地化字符串。
        /// </summary>
        internal static string CheckMsg {
            get {
                return ResourceManager.GetString("CheckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D:\work\开发流程及笔记 的本地化字符串。
        /// </summary>
        internal static string DefaultPath {
            get {
                return ResourceManager.GetString("DefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前编辑内容没保存,确认退出么？ 的本地化字符串。
        /// </summary>
        internal static string ExitMsg {
            get {
                return ResourceManager.GetString("ExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出提示 的本地化字符串。
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D:\work\开发流程及笔记\2017 的本地化字符串。
        /// </summary>
        internal static string OpenDefaultPath {
            get {
                return ResourceManager.GetString("OpenDefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取文件,请留意文本格式! 的本地化字符串。
        /// </summary>
        internal static string ReadFileErr {
            get {
                return ResourceManager.GetString("ReadFileErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径不符合要求，请重试！需包好年份信息 的本地化字符串。
        /// </summary>
        internal static string ReadPathErr {
            get {
                return ResourceManager.GetString("ReadPathErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息保存错误，请检查 的本地化字符串。
        /// </summary>
        internal static string SaveErrMsg {
            get {
                return ResourceManager.GetString("SaveErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息保存成功！ 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessMsg {
            get {
                return ResourceManager.GetString("SaveSuccessMsg", resourceCulture);
            }
        }
    }
}
