//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevLogHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDevCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDevCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevLogHelper.Resources.ResourceDevCode", typeof(ResourceDevCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 脚本生成成功，记得修改SqlDbType类型和对应的参数！！已复制到剪切板 的本地化字符串。
        /// </summary>
        internal static string BaseSqlTip {
            get {
                return ResourceManager.GetString("BaseSqlTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入参数和对应的sql条件 的本地化字符串。
        /// </summary>
        internal static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少输入一条字段信息 的本地化字符串。
        /// </summary>
        internal static string FieldsEmpty {
            get {
                return ResourceManager.GetString("FieldsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入方法名 的本地化字符串。
        /// </summary>
        internal static string MethodEmpty {
            get {
                return ResourceManager.GetString("MethodEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入排序字段 的本地化字符串。
        /// </summary>
        internal static string OrderEmpty {
            get {
                return ResourceManager.GetString("OrderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入查询语句 的本地化字符串。
        /// </summary>
        internal static string QuerySqlEmpty {
            get {
                return ResourceManager.GetString("QuerySqlEmpty", resourceCulture);
            }
        }
    }
}
